### ISSUE TITLE
Problem with generatedSources

### ISSUE THREAD

**Issue by robmoffat** [tcawley/gradle-protobuf-plugin#5]
Hi,

Thanks for writing this excellent plugin.  I'm not a massive expert on Gradle, but I am having an issue with one of our subprojects.  Unfortunately, we are generating a .proto file from an xml definition held elsewhere.   I am storing this in 

new File(buildDir.path, "generated-sources/proto")

However, when your protobuf plugin kicks off, it looks for this input directory, but it hasn't been created yet.  So I get this error:

```
Caused by: java.io.FileNotFoundException: C:\Users\rmoffat\java\REF\dsl\branches\2.0-Strategic\re.protobuf\build\generated-sources\proto
        at com.tomcawley.tasks.ProtoBufCompileTask.getProtoFiles(ProtoBufCompileTask.groovy:89)
        at com.tomcawley.tasks.ProtoBufCompileTask_Decorated.getProtoFiles(Unknown Source)
        at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:216)
        at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:122)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
        at com.tomcawley.tasks.ProtoBufCompileTask_Decorated.invokeMethod(Unknown Source)
        at org.gradle.util.ReflectionUtil.invoke(ReflectionUtil.groovy:23)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$PropertyInfo.getValue(AnnotationProcessingTaskFactory.java:369)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$Validator$1.call(AnnotationProcessingTaskFactory.java:182)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:120)
        ... 50 more
```

So, it's looking for the generated source directory before it's been created.  Not really sure how to get around this problem.  Any thoughts?

thanks,

Rob

**Comment by robmoffat** [comment]
My bad, the directory didn't exist and the plugin crashed.
